# Generated by Django 5.2.9 on 2025-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='cert_type',
        ),
        migrations.AddField(
            model_name='certification',
            name='category',
            field=models.CharField(choices=[('achievements', 'Achievements'), ('certificate', 'Certificate'), ('participation', 'Participation')], default='certificate', max_length=50),
        ),
    ]
