# Generated by Django 5.2.9 on 2025-12-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_skill_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
