# Generated by Django 5.2.9 on 2025-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_skill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('platform', 'Platform'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
