# Generated by Django 5.2.9 on 2025-12-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload icon image (optional)', null=True, upload_to='skills/icons/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or text icon', max_length=50),
        ),
    ]
