# Generated by Django 5.2.9 on 2025-12-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_skill_icon_image_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hackerrank_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
